const Homeproduct =
[
    {
        id: 1,
        Name: 'product1',
        price: '26',
        image: 'image/1.webp',
        cat: 'fruit',
        type: 'new',
    },
    {
        id: 2,
        Name: 'product2',
        price: '96',
        image: 'image/2.webp',
        cat: 'fruit',
        type: 'new',
    },
    {
        id: 3,
        Name: 'product3',
        price: '236',
        image: 'image/3.webp',
        cat: 'fruit',
        type: 'new',
    },
    {
        id: 4,
        Name: 'product4',
        price: '636',
        image: 'image/bread.jpg',
        cat: 'bread',
        type: 'new',
        info:'HELLO BREAAD'
    },
    {
        id: 5,
        Name: 'product5',
        price: '98',
        image: 'image/4.webp',
        cat: 'Vegetables',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'product6',
        price: '59',
        image: 'image/5.webp',
        cat: 'Vegetables',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'product7',
        price: '956',
        image: 'image/6.webp',
        cat: 'fruit',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'product8',
        price: '389',
        image: 'image/7.webp',
        cat: 'Vegetables',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'product9',
        price: '67',
        image: 'image/8.webp',
        cat: 'Vegetables',
        type: 'top',
    },
    {
        id: 10,
        Name: 'product10',
        price: '76',
        image: 'image/9.webp',
        cat: 'fruit',
        type: 'top',
    },
    {
        id: 11,
        Name: 'product11',
        price: '87',
        image: 'image/10.webp',
        cat: 'Vegetables',
        type: 'top',
    },
    {
        id: 12,
        Name: 'product12',
        price: '807',
        image: 'image/12.jpg',
        cat: 'Coldrinks',
        type: 'top',
    },
    {
        id: 13,
        Name: 'product12',
        price: '807',
        image: 'image/13.jpg',
        cat: 'Coldrinks',
        type: 'top',
    },
    {
        id: 14,
        Name: 'product12',
        price: '807',
        image: 'image/14.jpg',
        cat: 'Coldrinks',
        type: 'top',
    },
    {
        id: 15,
        Name: 'product12',
        price: '120',
        image: 'image/15.jpg',
        cat: 'chocolates',
        type: 'top',
    },
    {
        id: 16,
        Name: 'product12',
        price: '75',
        image: 'image/16.jpg',
        cat: 'chocolates',
        type: 'top',
    },
]
export default Homeproduct